- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.buitin.dnf
      name: "{{ items }}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix
